---
title: "Jul PCA"
output: html_notebook
---

```{r}
library(devtools)
#install_github("cran/FactoMineR")
#install_github("cran/factoextra")
library(FactoMineR)
library(factoextra)
```


Reading Data in and formatting how PCA function wants it
```{r}
Jul_data <- read.csv("C:/Users/nickbrowen/Desktop/STAT Summer Research/JulSoil.csv")[,-1]
Jul <- data.frame(Jul_data[c(-1,-10)], row.names = Jul_data$Order)
```

Running PCA
```{r}
Jul_res <- PCA(Jul, graph = F, scale.unit = F)
Jul.pca.prcomp <- prcomp(Jul, scale = F)
summary(Jul_res)
Jul_eigval <- Jul_res$eig #eigenvalues
Jul_eigvec <- Jul.pca.prcomp$rotation
```

Scree Plot
```{r}
fviz_eig(Jul_res, addlabels = TRUE)
```

Scatterplot of observations by dim1 and dim2
```{r}
fviz_pca_ind(Jul_res, label = "none")
```

Correlations between dimensions and variables
```{r}
Jul_res.desc <- dimdesc(Jul_res, axes = c(1,2), proba = 1)

#Description of dimension 1
Jul_res.desc$Dim.1

# Description of dimension 2
Jul_res.desc$Dim.2

```
```
text
```
```{r}
fviz_pca_var(Jul_res, col.var = "contrib", repel = T)
```

```{r}
fviz_contrib(Jul_res, choice = "var")
```

