---
title: "PCA for March 2017"
output: html_notebook
---


```{r}
library(devtools)
#install_github("cran/FactoMineR")
#install_github("cran/factoextra")
library(FactoMineR)
library(factoextra)
```


Reading Data in and formatting how PCA function wants it
```{r}
Mar_data <- read.csv("C:/Users/nickbrowen/Desktop/STAT Summer Research/MarSoil.csv")[,-1]
Mar <- data.frame(Mar_data[c(-1,-10)], row.names = Mar_data$Order)
```

Running PCA
```{r}
Mar_res <- PCA(Mar, graph = F, scale.unit = F)
Mar.pca.prcomp <- prcomp(Mar, scale = F)
summary(Mar_res)
Mar_eigval <- Mar_res$eig #eigenvalues
Mar_eigvec <- Mar.pca.prcomp$rotation
```

Scree Plot
```{r}
fviz_eig(Mar_res, addlabels = TRUE)
```

Scatterplot of observations by dim1 and dim2
```{r}
fviz_pca_ind(Mar_res, label = "none")
```

Correlations between dimensions and variables
```{r}
Mar_res.desc <- dimdesc(Mar_res, axes = c(1,2), proba = 1)

#Description of dimension 1
Mar_res.desc$Dim.1

# Description of dimension 2
Mar_res.desc$Dim.2

```
```
It seems that every variable is apart of component 1 (which doesnt seem useful at all). Every correlation is above .96.
```

Individual Contributions to Dim1
```{r}
fviz_contrib(Mar_res, choice = "ind")
```
```{r}
tail(sort(Mar_res$ind$contrib[,1]), 5)
```
```
Sphingobacteriales is contributing a massive amount to dim1. I tried removing just that row from the data set to see how it was affecting the PCA, but nothing changed much at all (i.e. Mar[-114,]).
```

```{r}
fviz_pca_var(Mar_res, col.var = "contrib", repel = T)
```


```{r}
fviz_contrib(Mar_res, choice = "var", axes = 1)
sort(Mar_res$var$contrib[,1], decreasing = T)
```
```
From assessing variable contributions to the first principal component, OF, NF, SF, NH, and H contribute most to variability in March. Out of these, OF is clearly the largest contributor. These are all positively correlated with the first principal component. This first dimension seems to be defined by the fertilizer and herbicide levels, suggesting that these are the most important variables in the Bud Break season.
```



