---
title: "May PCA"
output: html_notebook
---

```{r}
library(devtools)
#install_github("cran/FactoMineR")
#install_github("cran/factoextra")
library(FactoMineR)
library(factoextra)
```


Reading Data in and formatting how PCA function wants it
```{r}
May_data <- read.csv("C:/Users/nickbrowen/Desktop/STAT Summer Research/MaySoil.csv")[,-1]
May <- data.frame(May_data[c(-1,-10)], row.names = May_data$Order)

```

Running PCA
```{r}
May_res <- PCA(May, graph = F, scale.unit = F)
May.pca.prcomp <- prcomp(May, scale = F)
summary(May_res)
May_eigval <- May_res$eig #eigenvalues
May_eigvec <- May.pca.prcomp$rotation
```

Scree Plot
```{r}
fviz_eig(May_res, addlabels = TRUE)
```

Scatterplot of observations by dim1 and dim2
```{r}
fviz_pca_ind(May_res, label = "none")
```

Correlations between dimensions and variables
```{r}
May_res.desc <- dimdesc(May_res, axes = c(1,2), proba = 1)

#Description of dimension 1
May_res.desc$Dim.1

# Description of dimension 2
May_res.desc$Dim.2

```
```
text
```

```{r}
fviz_pca_var(May_res, col.var = "contrib", repel = T)
```


```{r}
fviz_contrib(May_res, choice = "var")
```


