---
title: "Sep PCA"
output: html_notebook
---

```{r}
library(devtools)
#install_github("cran/FactoMineR")
#install_github("cran/factoextra")
library(FactoMineR)
library(factoextra)
```


Reading Data in and formatting how PCA function wants it
```{r}
Sep_data <- read.csv("C:/Users/nickbrowen/Desktop/STAT Summer Research/SepSoil.csv")[,-1]
Sep <- data.frame(Sep_data[-c(1,10)], row.names = Sep_data$Order)
```

Running PCA
```{r}
Sep_res <- PCA(Sep, graph = F, scale.unit = F)
Sep.pca.prcomp <- prcomp(Sep, scale = F)
summary(Sep_res)
Sep_eigval <- Sep_res$eig #eigenvalues
Sep_eigvec <- Sep.pca.prcomp$rotation
```

Scree Plot
```{r}
fviz_eig(Sep_res, addlabels = TRUE)
```

Scatterplot of observations by dim1 and dim2
```{r}
fviz_pca_ind(Sep_res, label = "none")
```

Correlations between dimensions and variables
```{r}
Sep_res.desc <- dimdesc(Sep_res, axes = c(1,2), proba = 1)

#Description of dimension 1
Sep_res.desc$Dim.1

# Description of dimension 2
Sep_res.desc$Dim.2

```
```
text
```
```{r}
fviz_pca_var(Sep_res, col.var = "contrib", repel = T)
```

```{r}
fviz_contrib(Sep_res, choice = "var")
```


